version: "3"
services:

  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=echodb
      - MYSQL_USER=echo
      - MYSQL_PASSWORD=echo
    ports:
      - 3306:3306

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=echo
      - POSTGRES_PASSWORD=echo
      - POSTGRES_DB=echodb
    ports:
    - 5432:5432